name: Manual Sync Main to Prod

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push main to prod
        run: |
          git checkout prod || git checkout -b prod
          git merge origin/main --no-edit
          git push origin prod
